apiVersion: v1
kind: Secret
metadata:
  name: jwt-shared-secret
  namespace: default
  labels:
    konghq.com/credential: jwt
type: Opaque
stringData:
  key: "fcg-auth-api"
  algorithm: "HS256"
  secret: "uma-chave-grande-e-secreta-para-jwt"